# NumPy

# NumPy Arrays

In [2]:
import numpy as np

In [6]:
my_list=[1,2,3]
arr=np.array(my_list)
arr

array([1, 2, 3])

In [7]:
my_mat=[[1,2,3], [4,5,6],[7,8,9]]
mat=np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# similar to range() built in function
ara=np.arange(0,10,2) # 10 is not included
ara

array([0, 2, 4, 6, 8])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.linspace(0,5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Ranom numbers

In [19]:
arr=np.random.rand(5)
arr

array([0.02947292, 0.20009949, 0.74379433, 0.71914855, 0.16923783])

In [20]:
arr=np.random.rand(2,3)
arr

array([[0.51301419, 0.97395135, 0.90726614],
       [0.10653932, 0.91307367, 0.73839271]])

In [21]:
arr=np.random.randn(2,3) #normal, gauss
arr

array([[-7.73100273e-01, -6.84540737e-01,  9.69670768e-01],
       [-1.28685216e+00, -8.65607266e-01,  1.09698694e-03]])

In [22]:
arr=np.random.randint(-5,5, 2) #5 no 
arr

array([-2, -3])

In [24]:
arr=np.random.randint(-5,5, (2,3)) #-5 inclusive, 5 - non-inclusive
arr

array([[-5,  0,  3],
       [-1, -1, -4]])

### Atributes and Methodf od Arrays

In [45]:
arr=np.arange(20)
print(arr)
print(arr.shape)

arr45=arr.reshape(4,5)
print(arr45)
print(arr45.shape)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [48]:
np.random.seed(101)

ranarr=np.random.randint(0,50,10)
ranarr

maximum=ranarr.max()
max_index=ranarr.argmax()

print(f'Max {maximum} on {max_index} position')
print(ranarr.dtype)

Max 47 on 6 position
int32


## Numpy Indexing and Selecting

In [49]:
import numpy as np

In [50]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr[1:9:2]

array([1, 3, 5, 7])

In [53]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:4]=99
print(slice_of_arr)
print(arr) # use copy!

[99 99 99 99  4  5]
[99 99 99 99  4  5  6  7  8  9 10]


In [56]:
arr=np.arange(0,11)
slice_of_arr=arr[0:6].copy() # here is copy!
slice_of_arr[:4]=99
print(slice_of_arr)
print(arr)

[99 99 99 99  4  5]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [58]:
arr_2d=np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
# it is the same
print(arr_2d[0][1])
print(arr_2d[0,1])

10
10


In [62]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [67]:
bool_arr=arr>5
print(bool_arr)
arr[bool_arr]

[False False False False False False  True  True  True  True  True]


array([ 6,  7,  8,  9, 10])

In [66]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [70]:
arr_2d=np.arange(0,50).reshape(5,10)
print(arr_2d)
print('---------------------')
print(arr_2d[1:4,1:9])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
---------------------
[[11 12 13 14 15 16 17 18]
 [21 22 23 24 25 26 27 28]
 [31 32 33 34 35 36 37 38]]


## NumPy Operations

In [71]:
import numpy as np

In [72]:
arr =np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [74]:
arr**arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [75]:
arr/arr # 0/0 - nan

<ipython-input-75-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [78]:
1/arr # 1/0 > inf (infinitive)

<ipython-input-78-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [79]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [80]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [81]:
print(np.max(arr))
print(arr.max())

10
10


In [82]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])